FROM pytorch/pytorch:2.9.1-cuda13.0-cudnn9-devel

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

RUN sed -i 's/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/security.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list

# install dependencies
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  wget \
  curl \
  libgtest-dev \
  libtinfo-dev \
  libedit-dev \
  libxml2-dev \
  libprotobuf-dev \
  protobuf-compiler \
  zlib1g-dev \
  libgflags-dev \
  libsqlite3-dev \
  llvm-dev \
  python3 \
  python3-dev \
  python3-setuptools \
  gcc \
  cmake \
  openssh-server \
  ninja-build \
  && \
  apt-get clean autoclean && \
  rm -rf /var/lib/apt/lists/*

# install gtest
RUN git clone https://github.com/google/googletest.git \
  && cd googletest \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make \
  && make install \
  && cd .. \
  && rm -rf ./googletest

COPY requirements-lint.txt requirements-dev.txt /workspace/
RUN pip install --upgrade pip \
  && pip install -r /workspace/requirements-lint.txt -r /workspace/requirements-dev.txt

RUN echo "LC_ALL=en_US.UTF-8" >> /etc/environment

# Configure SSH
RUN mkdir -p /var/run/sshd && \
  echo 'root:sunlune' | chpasswd && \
  sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
  sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
  sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config && \
  mkdir -p /root/.ssh && chmod 700 /root/.ssh

# Expose SSH port
EXPOSE 22

# install claude code
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash && \
    . "$HOME/.nvm/nvm.sh" && \
    nvm install 22 && \
    node -v && nvm current && npm -v && \
    npm install -g @anthropic-ai/claude-code ccusage

WORKDIR /workspace

CMD ["/bin/bash"]